
define SYSUSER_PWD='&1'
define ORACLE_DBNAME='&2'
define REDOLOG_DEST1='&3'
define REDOLOG_DEST2='&4'

connect "SYS"/"&&SYSUSER_PWD" as SYSDBA

set echo on

spool $SCRIPTS/postDBCreation.log append

ALTER DATABASE 
  ADD LOGFILE THREAD 3 
				GROUP 21 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_21.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_21.log') SIZE 256M,
        GROUP 22 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_22.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_22.log') SIZE 256M,
        GROUP 23 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_23.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_23.log') SIZE 256M,
				GROUP 24 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_24.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_24.log') SIZE 256M,
				GROUP 25 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_25.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_25.log') SIZE 256M,
				GROUP 26 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_26.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_26.log') SIZE 256M,
				GROUP 27 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_27.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_27.log') SIZE 256M,
				GROUP 28 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_28.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_28.log') SIZE 256M,
				GROUP 29 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_29.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_29.log') SIZE 256M,
				GROUP 30 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_30.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_30.log') SIZE 256M
/

ALTER DATABASE ENABLE PUBLIC THREAD 3;

spool off

exit;

