
define SYSUSER_PWD='&1'
define ORACLE_DBNAME='&2'
define REDOLOG_DEST1='&3'
define REDOLOG_DEST2='&4'

connect "SYS"/"&&SYSUSER_PWD" as SYSDBA

set echo on
spool $SCRIPTS/postDBCreation.log append

ALTER DATABASE 
  ADD LOGFILE THREAD 2 
				GROUP 11 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_11.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_11.log') SIZE 256M,
        GROUP 12 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_12.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_12.log') SIZE 256M,
        GROUP 13 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_13.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_13.log') SIZE 256M,
				GROUP 14 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_14.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_14.log') SIZE 256M,
				GROUP 15 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_15.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_15.log') SIZE 256M,
				GROUP 16 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_16.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_16.log') SIZE 256M,
				GROUP 17 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_17.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_17.log') SIZE 256M,
				GROUP 18 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_18.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_18.log') SIZE 256M,
				GROUP 19 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_19.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_19.log') SIZE 256M,
				GROUP 20 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redoA_20.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redob_20.log') SIZE 256M
/

ALTER DATABASE ENABLE PUBLIC THREAD 2;

spool off
exit;

