define SYSUSER_PWD='&1'
define USER_TAB_LOC='&2'

connect "SYS"/"&&SYSUSER_PWD" as SYSDBA
set echo on

spool $SCRIPTS/CreateDBFiles.log append

CREATE SMALLFILE TABLESPACE "USERS" LOGGING 
DATAFILE '&&USER_TAB_LOC' 
SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/

ALTER DATABASE DEFAULT TABLESPACE "USERS";

spool off

exit

