define SYSUSER_PWD='&1'
define ORACLE_DBNAME='&2'
define REDOLOG_DEST1='&3'
define REDOLOG_DEST2='&4'
define SYSTEM_TAB_LOC='&5'
define SYSAUX_TAB_LOC='&6'
define TEMP_TAB_LOC='&7'
define UNDO_TAB_LOC='&8'
define CHARACTER_SET ='&9'
define SYSTEM_USER_PWD ='&10'

prompt ===== Create Database with this parameter ========

prompt SYSUSER_PWD     =***************
prompt ORACLE_DBNAME   = &&ORACLE_DBNAME
prompt REDOLOG_DEST1   = &&REDOLOG_DEST1
prompt REDOLOG_DEST2   = &&REDOLOG_DEST2
prompt SYSTEM_TAB_LOC  = &&SYSTEM_TAB_LOC
prompt SYSAUX_TAB_LOC  = &&SYSAUX_TAB_LOC
prompt TEMP_TAB_LOC    = &&TEMP_TAB_LOC
prompt UNDO_TAB_LOC    = &&UNDO_TAB_LOC
prompt CHARACTER_SET   = &&CHARACTER_SET
prompt SYSTEM_USER_PWD =***************


prompt =================================================



connect "SYS"/"&&SYSUSER_PWD" as SYSDBA

set echo on

spool $SCRIPTS/CreateDB.log append

startup nomount pfile="$SCRIPTS/init.ora"

CREATE DATABASE "&&ORACLE_DBNAME"
MAXINSTANCES 32
MAXLOGHISTORY 1
MAXLOGFILES 192
MAXLOGMEMBERS 3
MAXDATAFILES 1024
       DATAFILE '&&SYSTEM_TAB_LOC' SIZE 600M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE '&&SYSAUX_TAB_LOC' SIZE 600M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '&&TEMP_TAB_LOC' SIZE  20M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE '&&UNDO_TAB_LOC'        SIZE 200M REUSE AUTOEXTEND ON NEXT  10240K MAXSIZE UNLIMITED
CHARACTER SET &&CHARACTER_SET
NATIONAL CHARACTER SET AL16UTF16
LOGFILE GROUP 1  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_01.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_01.log') SIZE 256M,
        GROUP 2  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_02.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_02.log') SIZE 256M,
        GROUP 3  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_03.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_03.log') SIZE 256M,
		GROUP 4  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_04.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_04.log') SIZE 256M,
		GROUP 5  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_05.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_05.log') SIZE 256M,
		GROUP 6  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_06.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_06.log') SIZE 256M,
		GROUP 7  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_07.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_07.log') SIZE 256M,
		GROUP 8  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_08.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_08.log') SIZE 256M,
		GROUP 9  ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_09.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_09.log') SIZE 256M,
		GROUP 10 ('&&REDOLOG_DEST1/&&ORACLE_DBNAME/redo_a_10.log', '&&REDOLOG_DEST2/&&ORACLE_DBNAME/redo_b_10.log') SIZE 256M
USER SYS IDENTIFIED BY "&&SYSUSER_PWD" USER SYSTEM IDENTIFIED BY "&&SYSTEM_USER_PWD"
/

spool off
exit

